### PR TITLE
Try osx_arm64 and linux_aarch64

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This is necessary for building QGIS in osx_arm64 and linux_aarch64
conda-forge/qgis-feedstock#289

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
Apparently this is working. @gillins can you please give a look and see it is useful for QGIS?

**Comment by gillins** [comment]
Looks good to me!

**Comment by gillins** [comment]
Actually should probably have `${CMAKE_ARGS}` passed in to the `cmake` command to ensure all ok for cross compiling.

**Comment by SrNetoChan** [comment]
@gillins Done. thanks for the pointers

**Comment by SrNetoChan** [comment]
@ceholden can we merge this one?

**Comment by gillins** [comment]
@SrNetoChan I don't think @ceholden is contributing to conda-forge ATM. Maybe add us both to `recipe-maintainers`? We'll find someone to merge this for us.

**Comment by SrNetoChan** [comment]
@gillins Done

@ocefpaf sorry to bother, do you know who can merge this?

**Comment by gillins** [comment]
@hmaarrfk can you merge this for us? Thanks!

**Comment by gillins** [comment]
Thanks!

**Pull request merged**
